tattle-made/Uli

browser extension/plugin/.husky/pre-commit
browser extension/plugin/.npmrc
browser extension/plugin/package-lock.json
browser extension/plugin/package.json

Fixes #46 
- Added husky as dev dependency
- Added husky prepare script
- Added node and npm engine versions with engine-strict enforcement
- Added pre-commit hooks for audit with failure at moderate audit level

Add audit pre-commit hooks

---

browser extension/plugin/manifest.firefox.json
browser extension/plugin/src/content-script.js
browser extension/plugin/src/service-screenshot.js
browser extension/plugin/src/transform.js
browser extension/plugin/src/twitter/tweet-controls.jsx

Added `manifest.firefox.yaml` which works on firefox.
```
cp manifest.firefox.yaml manifest.yaml
npm run build
```
Now test the newly built add on from the dist folder in firefox developer edition as mentioned [here](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/). You can load the manifest.yaml from the dist folder as a temporary add on.
https://extensionworkshop.com/documentation/publish/ - Haven't explored this yet. I guess it's better if some core member of tattle does this :)
1. When the twitter background is dark, the screenshot had white text on white background. Updated to set the backgound as per the twitter background.
2. The inline controls would show up multiple times. I could replicate this on firefox all the time, and sometimes on …

Firefox support + A few bugfixes

---

uli-website/src/components/molecules/AppShell.jsx

The problem was occurring because of the relative path of the file with the background color being present rather than the absolute path

fix: refresh does not change background color. Resolves #167

---

browser-extension/plugin/src/content-script.js
browser-extension/plugin/src/transform-v2.js
browser-extension/plugin/src/twitter/parser-v2.js

The earlier parser detected tweets by using RegEx queries and matching the Xpath to the tweet text elements with certain given Xpaths. 
However, I discovered that every DIV on the twitter DOM that contains a tweet text has an attribute titled 'data-testid' whose value is always 'tweetText'
Hence, the new  method uses the 'querySelectorAll()' method (ref: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) of the DOM in order to select all such DIVs whose data-testid is set to tweetText. This gives an array of all DIVs in the current DOM that contain the spans which contains the tweetText. 
This array is discovered in the file parser-v2.js and then sent to the file transform-v2.js and processed there where a for loop runs through all the DIVs and does the processing …

Rewrote existing parser with a new logic to detect tweets

---

browser-extension/plugin/package-lock.json
browser-extension/plugin/src/content-script.js
browser-extension/plugin/src/transform-general.js

- Fixed Uli site rendering issues
- Fixed dynamic page loading issues
- Updated update-browserslist-db@latest
Edge case handling
- https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
```
textContent gets the content of all elements, including <script> and <style> elements. In contrast, innerText only shows "human-readable" elements.
```
- Closes issue #254

Fix Uli slur redaction for general websites

---

.github/workflows/create-plugin-release.yml

- Modified Uli project url
- Updated actions/checkout version
- Updated deprecated set-output command
Reference:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Update github release workflow

---

browser-extension/plugin/manifest.firefox.json
browser-extension/plugin/manifest.json
browser-extension/plugin/src/content-script.js
browser-extension/plugin/src/transform-general.js
browser-extension/plugin/src/ui-components/atoms/Toggle.css
browser-extension/plugin/src/ui-components/atoms/ToggleSwitchCustom.js
browser-extension/plugin/src/ui-components/pages/App.jsx
browser-extension/plugin/src/ui-components/pages/Off.jsx
browser-extension/plugin/src/ui-components/pages/Preferences.jsx

This pull request aims to add a feature and resolve a bug. 
1. An On/Off button is added
- this is a custom toggle switch that allows users to turn Uli on and off. A reload of the page is required for changes to be implemented.
- A reload is also required when the user login's to Uli for the first time, i.e. activates an account.
2. Issue #314 is also fixed in this PR. 
- Uli no longer makes the text revered in text input areas.

adding on-off button, fixing reverse text

---

browser-extension/api-server/.husky/pre-commit
browser-extension/api-server/Dockerfile

- Added ignore-scripts flag to api-server Dockerfile
- Fixed husky pre-commit folder name in api-server
- This fixes https://github.com/tattle-made/security/issues/20

Add ignore-scripts flag

---

browser-extension/plugin/package.json

We will have to go back to the original code of `npm run dev:options` as that is required to load the frontend in the browser extension.

fix: re- parcel error 

---

browser-extension/api-server/s3.js

- Added upload file size limits
- This fixes https://github.com/tattle-made/security/issues/14

Fix potential DoS

---

browser-extension/api-server/.dockerignore
browser-extension/api-server/Dockerfile

- Updated node alpine image version with explicit digest
- Optimized node tooling for production
- Changed ownership of copied files
- Updated .dockerignore
- This addresses https://github.com/tattle-made/security/issues/26

Harden dockerfile

---

browser-extension/plugin/src/content-script.js

When a user login's to Uli for the first time and add a word to the `Slur List` in `prefrences`. The word `undefined` is also added in front of the word. For instance, if I want to select right click and add the word `measure` to my `slur list`, then right now its being getting added like this
1. Modified the logic in the `content-script.js` file to handle the slur addition
2. Previously, when the preference data (`pref`) was not defined, the code attempted to spread `undefined` values into the new object when updating slurList. This occurs when the user activates the account and just tries to add a slur word. I fixed this by checking if `pref` or `pref.slurList` is `undefined` and directly assigning the value of the slur to `slurList`
@dennyabrain just to make sure its not some issue on …

fix: undefined is being added to Slur list when added using right click

---

uli-website/src/pages/hidden-words-for-thread.jsx

---
name: Edit Slur words in UI
about: https://github.com/tattle-made/Uli/issues/381
title: ''feat: user can edit slur words in hidden words for thread on uli-website
labels: feature enhancement
assignees: ''
---
I made relevant changes to the codebase to ensure that we can edit as well as add characters to the TextBox.
**Steps to test the PR**
Simply run the server and navigate to /hidden-words-for-thread/
**Expected behavior**
Delete on backspace and type any character to add.
**Screenshots**
N/A
**Additional context**
N/A

feat: user can edit slur words in hidden words for thread on uli-website

---

browser-extension/plugin/manifest.json

This PR changes how we add permissions to the `manifest.json` file.
@duggalsu pointed out that Manifest v3 does not recommend adding URL's to `permissions`, instead they suggest we add URL's to `host_permissions` 
`host_permissions` - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions
I have made this change for `manifest.json` and tested out in chromium based browsers. I have not made this change for firefox as it still uses manifest v2
@dennyabrain you can review this at your time of comfort and then merge it

refactor: changing permission for url in manifest

---

browser-extension/plugin/src/background.js
browser-extension/plugin/src/content-script.js
browser-extension/plugin/src/ui-components/pages/Slur.jsx

This PR add two things
1. it resolves this issue - https://github.com/tattle-made/Uli/issues/423. Users can right click add a slur word to Uli, that word will be added to their `personal slur list` and also it will be `crowdsourced`.
2. I have added a loading bar to the `slur crowdsource` feature, as I noticed it takes a small fraction of a second in production for fetching slurs.
@dennyabrain can you review this PR and merge it. 
I have tested this PR on firefox, chrome and brave, things are working perfectly fine on my end.

feat: add slur and crowdsource slur on one click && feat: loading bar for slur crowdsource

---

browser-extension/plugin/src/content-script.js
browser-extension/plugin/src/transform-general.js

- Fixed redaction to work on initial page load without delay
- Also fixes redaction not working on local files as DOM is unchanged
This was done with @dennyabrain

Add slur redaction on initial page load

---

uli-website/src/pages/blog/cross-platform_pt 2

Part 2 of the work on cross platform abuse to upload on the website

Create cross-platform_pt 2

---

browser-extension/plugin/src/ui-components/pages/SlurCreate.jsx

---
name: small patch
about: Improve UI of Add Slur form
labels: enhancement
---
Relates to #409 
It's a small patch that adds a border to the *"What makes it problematic?"* text area and restricts reszing to only vertical.
**Before:** At first glance itself, the cursor feels like in a odd poisiton in the text area with a lot of gap between the border below. Allowing horizontal scroll makes it messier
https://github.com/tattle-made/Uli/assets/130062020/713da799-2a92-4a27-b217-057b2da8c3ed
After:
https://github.com/tattle-made/Uli/assets/130062020/49f76c92-c583-4970-a625-e7d70fe272cb

chore: Improve UI of Add Slur form

---

browser-extension/plugin/src/ui-components/pages/SlurEdit.jsx

---
name: Chore
about: style text-area in `SlurEdit` to be consistent with `SlurCreate`
labels: follow-up
---
Follow up PR for #550 
**Screenshots**

chore: style text-area in `SlurEdit` to be consistent with `SlurCreate`

---

uli-website/src/pages/blog/approach.mdx
uli-website/src/pages/blog/chisel-online-abuse.mdx
uli-website/src/pages/blog/cross-platform-pt1.mdx
uli-website/src/pages/blog/cross-platform_pt_2.mdx
uli-website/src/pages/blog/getting-started-with-aws-copilot.mdx
uli-website/src/pages/blog/making-of-August-2023.mdx
uli-website/src/pages/blog/making-of-dec-2021.mdx
uli-website/src/pages/blog/making-of-dec-2023.mdx
uli-website/src/pages/blog/making-of-feb-2022.mdx
uli-website/src/pages/blog/making-of-jan-2022.mdx
uli-website/src/pages/blog/making-of-mar-2022.mdx
uli-website/src/pages/blog/responsible-display.mdx
uli-website/src/pages/blog/silencing-impact-OGBV.mdx
uli-website/src/pages/blog/tech4dev-user-research-lessons.mdx
uli-website/src/pages/blog/uli-privacy.mdx

---
name: [uli-website]: order blogs in descending order of date #557
about: order blogs in descending order of date
---
This PR improves the order blogs in descending order of date.
Related to Issue https://github.com/tattle-made/Uli/issues/557.
Graphql query is right just needed to change date format of the Blog md files for sorting to be applicable.

Fix for #557: Order blogs in descending order of date

---

browser-extension/plugin/src/transform-general.js

---
name: uliStore v 1.0.0
about: Data structure preparation for efficient storage of slurs
---
PR is related to the discussion done in following comments
- [Comment 1](https://github.com/tattle-made/Uli/issues/583#issuecomment-2229974905)
- [Comment 2](https://github.com/tattle-made/Uli/issues/583#issuecomment-2230489649)
**Steps to test the PR**
Code is added to `plugin/src/transform-general.js`
**Screenshots**
- ![image](https://github.com/user-attachments/assets/8d09d7ea-2161-4e0f-a926-4085b9b13de6)
- ![image](https://github.com/user-attachments/assets/2f574c11-ffc9-4c64-b05f-88d32ce7483e)
- ![image](https://github.com/user-attachments/assets/4c74d059-079b-448f-b16e-e43faaa23d36)
- ![image](https://github.com/user-attachments/assets/b8b683df-5327-42b2-9961-1f547af7f …

[#544] Added uliStore data structure, `getAllTextNodes()` and `locateSlur()` functions

---

browser-extension/plugin/.env.development
browser-extension/plugin/src/api.js
browser-extension/plugin/src/ui-components/pages/App.jsx
browser-extension/plugin/src/ui-components/pages/Debug.jsx
browser-extension/plugin/src/ui-components/pages/SlurCreate.jsx
uli-community/lib/uli_community/user_contribution.ex
uli-community/lib/uli_community/user_contribution/crowdsourced_slur.ex
uli-community/lib/uli_community_web/controllers/user_session_controller_api.ex
uli-community/priv/repo/migrations/20250120074709_create_crowdsourced_slurs.exs
uli-community/test/support/fixtures/user_contribution_fixtures.ex
uli-community/test/uli_community/user_contribution_test.exs

This is a WIP PR. 
The following tasks were covered in this PR: 
- Created the user-contribution context along with the slurs table in the uli_community.
- In the plugin, completed the login functionality. 
CC: @aatmanvaidya

Uli comm backend

---

uli-community/assets/js/app.js
uli-community/assets/js/pie_chart.js
uli-community/lib/uli_community_web/controllers/dashboard_controller.ex
uli-community/lib/uli_community_web/controllers/dashboard_html/index.html.heex

This PR adds a simple pie chart on the dashboard page using data from the Elixir backend.
- Converted an Elixir map into **JSON** and passed it to JavaScript using a `<script>` tag.
- Rendered the pie chart using **D3.js** by accessing the` window.pieChartData`.
- Ensured LiveView doesn't interfere with the chart rendering using `phx-update="ignore"`.
- Added logic to prevent duplicate SVGs when the chart reloads.
This resolves issue [#769](https://github.com/tattle-made/Uli/issues/769).

Create pie chart using Elixir map data

---

uli-community/assets/js/app.js
uli-community/assets/js/hooks/source_bar_chart_hook.js
uli-community/assets/js/source_bar_chart.js
uli-community/lib/uli_community/user_contribution.ex
uli-community/lib/uli_community_web/live/dashboard_live.ex
uli-community/lib/uli_community_web/live/dashboard_live.html.heex

This pull request implements the feature described in [Issue #790](https://github.com/tattle-made/Uli/issues/790), which requires displaying a bar chart on the `/dashboard` page showing the number of slurs contributed from each source (such as expert, plugin, crowdsourcing_session). The chart is built using D3.js.
**Features Implemented:**
**1. API Added**
- Function:` get_source_distribution/0`
- Module: `UliCommunity.UserContribution`
- Description: Groups slurs by the `source` field and returns the count for each group.
```
def get_source_distribution do
CrowdsourcedSlur
|> group_by([s], s.source)
|> select([s], %{label: s.source, count: count(s.id)})
|> Repo.all()
end
```
**2. LiveView Update**
- File: `dashboard_live.ex`
- Description: Fetched source distribution data by calling the …

Add D3 bar chart to dashboard for slur source distribution

---

uli-community/assets/js/app.js
uli-community/assets/js/hooks/weekly_line_chart_hook.js
uli-community/assets/js/pie_chart.js
uli-community/assets/js/weekly_slur_line_chart.js
uli-community/lib/uli_community/user_contribution.ex
uli-community/lib/uli_community_web/live/dashboard_live.ex
uli-community/lib/uli_community_web/live/dashboard_live.html.heex

This PR solves [Issue #791](https://github.com/tattle-made/Uli/issues/791).
The goal of this issue was to show how many slurs were submitted every week, using a **line chart** on the `/dashboard` page. This chart helps us understand changes in submission activity over time.
**1. Wrote a backend function to get weekly data**
I created a function called `get_weekly_submission_counts/0` that fetches the number of slurs submitted each week.
Here’s what it does:
- It uses inserted_at from the crowdsourced_slurs table.
- Groups the data by week using PostgreSQL's date_trunc('week', inserted_at) function.
- Counts how many slurs were submitted in each week.
- Converts the date to a simple ISO format like "2025-06-04".
```
def get_weekly_submission_counts do
weekly_data =
Repo.all(
from(cs in …
```

Add weekly slur submission data aggregation and line chart to dashboard

---

uli-community/lib/uli_community/user_contribution.ex
uli-community/lib/uli_community_web/live/dashboard_live.ex
uli-community/lib/uli_community_web/live/dashboard_live.html.heex

**Related Issue:** [#792](https://github.com/tattle-made/Uli/issues/792)
This PR adds a simple display element on the `/dashboard` page that shows the **total number of unique slurs** present in the `crowdsourced_slurs `table.
**1. A new function `get_unique_slur_count/0` is added:**
```
def get_unique_slur_count do
Repo.one(
from(cs in CrowdsourcedSlur,
select: count(fragment("DISTINCT lower(?)", cs.label))
)
)
end
```
This query counts how many different (distinct) slur labels exist in the table.
It uses `lower(?)` to make sure the count is case-insensitive, so `Abuse` and `abuse` are treated as the same slur.
**2. This count is fetched in the LiveView and assigned to the socket:**
```
unique_slur_count =
try do
UserContribution.get_unique_slur_count()
rescue
_ -> nil
end
assign(socket, …
```

Add unique slur count display to Dashboard page

---

uli-community/lib/uli_community_web/components/core_components.ex
uli-community/lib/uli_community_web/live/crowdsource_contributions_live.html.heex

This pull request improves the responsiveness of the Crowdsource Contributions page, ensuring a smoother experience on smaller screens such as mobile devices and tablets.
1.**Search Bar**
- Made search bar responsive.
- Now takes full width on small screens and a fixed width on medium+ screens.
2. **"Showing all contributions" header**
- Adjusted heading styles to be responsive (`text-base sm:text-lg md:text-xl`).
- Ensures proper alignment in both mobile and desktop layouts.
3. **Sidebar (Filters section)**
- Sidebar filters (`left-side`) are now hidden on small screens (`hidden lg:flex`).
- Remain visible only on larger screens for better layout.
4. **Clear Filters button**
- Updated visibility: shown only on medium+ screens (`hidden md:inline-flex`).
5. **Mobile/Tablet Filter Drawer** …

Make Crowdsource Contributions page responsive for all screens
