tattle-made/Uli

browser extension/plugin/manifest.json

- Added CSP for plugin starting from a 'default deny' setting
See
- https://developers.google.com/web/fundamentals/security/csp
- https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy

Add plugin content security policy

---

browser extension/plugin/.husky/pre-commit
browser extension/plugin/.npmrc
browser extension/plugin/package-lock.json
browser extension/plugin/package.json

Revert "Add audit pre-commit hooks"

---

browser extension/plugin/.husky/pre-commit
browser extension/plugin/.npmrc
browser extension/plugin/package-lock.json
browser extension/plugin/package.json

Updated branch after changes were reverted

Add husky hooks

---

browser extension/plugin/.eslintrc.js
browser extension/plugin/README.md
browser extension/plugin/app-labels.md
browser extension/plugin/manifest.json
browser extension/plugin/notes.md
browser extension/plugin/options.html
browser extension/plugin/package-lock.json
browser extension/plugin/package.json

- Added prettier for code styling at precommit
- Fixed code styling for all plugin files

Add code styling

---

browser extension/api-server/.husky/pre-commit
browser extension/api-server/.npmrc
browser extension/api-server/package-lock.json
browser extension/api-server/package.json

- Added husky as dev dependency
- Added husky prepare script
- Added node and npm engine versions with engine-strict enforcement
- Added pre-commit hooks for audit with failure at moderate audit level
- Fixed issues caught by npm audit

Fix audit issues in api-server

---

FastAPI - OGBV/README.md

This resolves #127 for now. Had not tagged the issue so opened a new PR.

docs: elaborated the documentation and fixed a few errors

---

browser-extension/plugin/.husky/pre-commit
browser-extension/plugin/src/ui-components/pages/Resources.jsx

- Replaced `http` with `https` for all URL occurences in `Resources.jsx` - http://www.cybervictims.org/
- Updated husky pre-commit hook for successful commit - renamed folder path to `browser-extension`
- Fixed linting errors `no-unused-vars` caught at pre-commit in `Resources.jsx`
- pre-commit linting auto-formatted `Resources.jsx`

Replaced `http` with `https`

---

browser-extension/plugin/.husky/pre-commit
browser-extension/plugin/manifest.json
browser-extension/plugin/package-lock.json

- Added modified CSP
- Updated husky pre-commit folder path
- Modified `package-lock.json` with updated `node` and `npm` versioning

Add modified CSP

---

ogbv-ml-rest/text_scraper.py
ogbv-ml-rest/user_scraper.py

These contain documented codes that used the snscrape library in order to scrape English Tweets for the OGBV extension. This was done to test the extension and get insights about its behaviour, between 08-07-2022 and 15-08-2022.

feat: added scrapers used to scrape English tweets for the extension

---

ogbv-ml-rest/README.md
ogbv-ml-rest/slur_detection_tester.py

Also added relevant documentation to the README.md of ogbv-ml-rest for testing.

feat: added slur replacement feature tester for chrome. Addresses #180 and #186

---

.github/workflows/release-on-chrome.yml
.github/workflows/release-on-firefox.yml
browser-extension/README.md
browser-extension/plugin/manifest.firefox.json
browser-extension/plugin/manifest.json

- Updated Uli repo url in github workflows
- Updated github actions checkout version in github workflows
- Modified firefox publish job id in github workflows
- Updated chrome and firefox extension version in manifest
- Removed localhost from CSP in manifest for production
- Added plugin dev CSP instructions to readme

Prepare for release

---

browser-extension/api-server/package-lock.json
browser-extension/api-server/package.json

- This fixes issue https://github.com/tattle-made/security/issues/21

Updated multer version

---

browser-extension/api-server/Dockerfile

- This fixes https://github.com/tattle-made/security/issues/17

Modified node docker image user

---

browser-extension/api-server/index.js

- Disabled web technology fingerprinting
- This fixes https://github.com/tattle-made/security/issues/19

Disable fingerprinting

---

uli-website/src/components/molecules/NavBar.jsx

Adding `Blog` to the header section of the uli-website

feat: adding blog to the header section of the uli-website

---

uli-website/package-lock.json
uli-website/package.json
uli-website/src/components/molecules/ContentPageShell.jsx
uli-website/src/components/molecules/codeSnippet.jsx
uli-website/src/pages/blog/getting-started-with-aws-copilot.mdx

---
name: Code Snippet Highlight
about: Create a report to help us improve
title: ''
labels: Feature Enhancement
assignees: ''@plon-Susk7
---
Written custom code snippet highlighting code to highlight code snippets on blogs.
**Steps to test the PR**
npm run start on website folder. Then navigate to blog and click on first blog article.
**Expected behavior**
The code snippet is now has a dark background color.
**Screenshots**
**Additional context**
Nope

Changes made to code snippet

---

browser-extension/plugin/package.json

- Removed package 'process' as it is not required

Remove package 'process'

---

browser-extension/api-server/package-lock.json
browser-extension/api-server/package.json
browser-extension/plugin/package-lock.json
browser-extension/plugin/package.json

- Removed `busboy` package from api-server as it is not required
- Auto-added (by package `parcel`) and pinned `process` package in plugin

Modify dependencies

---

browser-extension/plugin/package-lock.json
browser-extension/plugin/package.json

- Updated parcel version
- Updated puppeteer version

Update non-breaking packages

---

browser-extension/plugin/test/slur_crowdsource_jest.test.js

updating the jest test for the axios REST API request of the slur crowdsource feature

fix: updating jest test for slur crowdsource apis

---

uli-website/package-lock.json
uli-website/package.json

- Updated `i18next` package in `uli-website`
- This closes issue #479

Update i18next package

---

uli-website/package-lock.json
uli-website/package.json

- Updated react package
- Updated react-dom package
- Updated react-i18next package

Update react in uli-website

---

browser-extension/api-server/package-lock.json
browser-extension/api-server/package.json
browser-extension/plugin/package-lock.json
browser-extension/plugin/package.json

- Updated non-breaking dependencies in `plugin` and `api-server`

Update non-breaking dependencies

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml

@dennyabrain I have tried fixing the github action - `deploy staging`. I removed the actions for the code moved to Uli legacy

fix: github action for deploy staging

---

browser-extension/plugin/manifest.firefox.json
browser-extension/plugin/manifest.json

chore: updating manifest version

---

browser-extension/plugin/src/twitter/tweet-controls.jsx

fix: axios import error

---

.github/workflows/close-inactive-issue.yml

adding a github action to close stale issues after 90 days

feat: action to close inactive issues

---

uli-website/src/pages/research.mdx

Adding the Dataset paper and Shared task to the research page

chore: updating research page

---

uli-website/src/pages/blog/cross-platform pt1

Part 1 of the blogs on cross-platform abuse online
---
name: Blog Approval
about: 
title: ''A Side of Whack-A-Mole"
labels: bug
assignees: ''kaustubhavarma"
---
The draft of the blog that needs to be uploaded has been submitted.

Cross-platform abuse blog upload 

---

browser-extension/plugin/src/transform-general.js

This PR is related to issue #625
- The blur functionality is implemented as explained in the issue.

feat: change meta data feature from icon to blur

---

uli-website/src/pages/blog/index.jsx

Added published date to blog list

---

uli-community/priv/repo/migrations/20250127055125_change_role_to_enum_and_change_default_role.exs

This PR has the following changes:
- created a migration file to make the user role an Enum and change the default user role from admin to user.

chore: make user role enum and change default role

---

browser-extension/plugin/src/transform-general.js

This is a WIP PR. 
This PR implements the feature to show slur metadata on infinite scrolling. We might need to test this out in various scenarios, especially for large websites like YouTube and Reddit. It is working on YouTube but on Reddit, the slurs are getting highlighted but on hovering them, the metadata is not visible. 
CC: @aatmanvaidya

feat: infinite loading in metadata WIP

---

uli-community/lib/uli_community_web/live/crowdsource_contributions_live.ex

This PR fixes the crowdsource slur order issue in uli-community.

fix: crowdsource slur order in uli-community

---

uli-community/lib/uli_community/user_contribution/crowdsourced_slur.ex
uli-community/priv/repo/migrations/20250515130815_add_source_and_session_id_to_crowdsourced_slurs.exs

chore: add source and session id to table

---

uli-community/assets/js/app.js
uli-community/assets/js/hooks/date-selector-hook.js
uli-community/lib/uli_community/user_contribution.ex
uli-community/lib/uli_community_web/components/core_components.ex
uli-community/lib/uli_community_web/live/crowdsource_contributions_live.ex
uli-community/lib/uli_community_web/live/crowdsource_contributions_live.html.heex
uli-community/lib/uli_community_web/live/crowdsource_contributions_search_params.ex

this PR resolves a part of https://github.com/tattle-made/Uli/issues/796 and https://github.com/tattle-made/Uli/issues/783
below a short video for the same
[Screencast from 18-06-25 05:45:59 PM IST.webm](https://github.com/user-attachments/assets/27fddb2f-891f-43bc-b28f-2ada9b2153ef)

feat: enable basic search and setup pagination
